services:
  crdb:
    image: cockroachdb/cockroach:v23.1.9
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=localhost
