services:
  worker:
    image: basin_worker:latest
    depends_on:
      - crdb
    ports:
      - 3000:3000
      - 3001:3001
    command: >
      --evm-wallet-pk=${EVM_WALLET_PK}
      --evm-contract-address=${EVM_CONTRACT_ADDRESS}
      --evm-provider-url=${EVM_PROVIDER_URL}
      --evm-chain-id=${EVM_CHAIN_ID}
      --export-bucket=${EXPORT_BUCKET}
      --export-credentials=${EXPORT_CREDENTIALS}
      --database-url=${DATABASE_URL}
      --bind-address=0.0.0.0:3000
      --bind-health-address=0.0.0.0:3001
      -vvvvv
  crdb:
    image: cockroachdb/cockroach:v23.1.9
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure --store=type=mem,size=0.5 --advertise-addr=localhost
  gcs:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443