apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: basin-staging

resources:
- ../base

configMapGenerator:
- envs:
  - configBasinWorker.env
  name: configmap-basin-worker
- envs:
  - configBasinExporter.env
  name: configmap-basin-exporter
images:
- name: textile/basin_exporter
  newName: bcalza/basin_worker
  newTag: latest
- name: textile/basin_worker
  newName: bcalza/basin_worker
  newTag: latest
