apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: basin-staging

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../base

configMapGenerator:
- envs:
  - configBasinWorker.env
  name: configmap-basin-worker
- envs:
  - configTcpServices.env
  name: configmap-basin-tcp-services

patches:
- path: ingress-controller-patch.json
  target:
    group: apps
    kind: Deployment
    name: ingress-nginx-controller
    version: v1
- path: ingress-patch.yaml