name: Format

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: format-${{github.ref}}
  cancel-in-progress: true

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --verbose

  tomlfmt:
   name: tomlfmt
   runs-on: ubuntu-latest
   steps:
     - name: Checkout source code
       uses: actions/checkout@master

     - name: Install Rust
       uses: actions-rs/toolchain@v1
       with:
         profile: minimal
         toolchain: nightly
         override: true

     - name: Install tomlfmt
       uses: actions-rs/install@v0.1
       with:
         crate: cargo-tomlfmt
         version: latest
         use-tool-cache: true

     - name: Run tomlfmt
       run: |
         cargo tomlfmt --dryrun
         (cd ./lib/evm; cargo tomlfmt --dryrun)
         (cd ./lib/exporter; cargo tomlfmt --dryrun)
         (cd ./lib/protocol; cargo tomlfmt --dryrun)
         (cd ./lib/worker; cargo tomlfmt --dryrun)
